### PR TITLE
TuningInstanceSingleCrit

### PR DESCRIPTION
**Pull request by be-marc**
## Marginal Plot - Each parameter versus performance

```r
autoplot(instance, type = "marginal") 
```

Screenshot_20210216_103002

## Performance Plot - Batch number versus performance

```r
autoplot(instance, type = "performance") 
```

Screenshot_20210216_103129

## Parameter Plot - Batch number versus parameter value

```r
autoplot(instance, type = "parameter") 
```

Screenshot_20210216_103303

## Parallel Coordinates Plot

```r
autoplot(instance, type = "parallel") 
```

Screenshot_20210217_161922

## Surface Plot

```r
autoplot(instance, type = "surface") 
```

Screenshot_20210217_174605

### CODE REVIEW

**Comment by mllg** [comment]
Can you extend/modify figures patched together with patchwork similar to regular ggplot2 plots?

If not, should we provide an option here to be able to access the list of plots?

**Comment by be-marc** [comment]
> Can you extend/modify figures patched together with patchwork similar to regular ggplot2 plots?

Yes `ggplot_build()` still works but a list option might be still useful. If you want arrange the plots in another way with patchwork or cowplot.

**Comment by be-marc** [comment]
## Scatter Plot

Two parameters versus performance drawn by filled points. This allows to use the scale package to adjust the x and y-axis. Useful if a transformation was used and the plotted points are overlapping. The surface plot does not work with the scale package, so we have this as an alternative. 

```r
library(scales) 
autoplot(instance, type = "points", trafo = TRUE) + 
  scale_x_continuous( 
    trans = log2_trans(), 
    breaks = trans_breaks("log2", function(x) 2^x), 
    labels = trans_format("log2", math_format(2^.x))) + 
  scale_y_continuous( 
    trans = log2_trans(), 
    breaks = trans_breaks("log2", function(x) 2^x), 
    labels = trans_format("log2", math_format(2^.x))) 
```

Screenshot_20210223_110119

**Comment by be-marc** [comment]
Return as list implemented.

**Pull request merged**
