### PR TITLE
Add plotpred2d

### PR DESCRIPTION
**Pull request by tpielok**
- Not sure if I found a good entry point for the code 
- I only took the 2D visualization capability

### CODE REVIEW

**Comment by jakob-r** [comment]
Note, this solves the same as #11 
(I know you know, but it is generally a good idea to have these things linked)

**Comment by pat-s** [comment]
So you did the same PR by chance almost at the same time? Should we decide for one? Can you maybe merge both or decide for one before we review both?

**Comment by tpielok** [comment]
I'm new to this project and just needed something which works for our course. IMO Jakobs approach is way more elegant, s.t. we can close my PR.

**Comment by pat-s** [comment]
Ok, thanks for the reply :) 

Feel free to contribute more if you want - a prior discussion in our mattermost channel might help to prevent such conflicts :)

**Pull request closed without merging**
