### PR TITLE
Fix density plots, add PredictionSurv

### PR DESCRIPTION
**Pull request by RaphaelS1**

### CODE REVIEW

**Comment by RaphaelS1** [comment]
This isn't essential until proba 0.2.3 on CRAN but is required to stop the book breaking when using GH versions (https://github.com/mlr-org/mlr3book/runs/1329451322)

**Comment by mllg** [comment]
Does this PR need the dev version of proba or not? I'm confused.

**Comment by RaphaelS1** [comment]
Yes but I'm doing a CRAN release now anyway (which will break viz) so you can merge this tomorrow if that's fine for you

**Comment by mllg** [comment]
Your change in `TaskDens.R` does not look like we need the dev version. Is proba now in Remotes to fix the book?

**Comment by mllg** [comment]
Alright, will merge tomorrow and update mlr3viz.

**Comment by RaphaelS1** [comment]
The autoplot uses `target_names` not `feature_names` which is why it breaks

**Pull request merged**
