### PR TITLE
plot learner prediction

### PR DESCRIPTION
**Pull request by jakob-r**
First draft of the learner prediction plot.
Based on the draft by @mllg.

### CODE REVIEW

**Comment by jakob-r** [comment]
> I'd like to use {vdiffr} for ggplot2 plot checking within tests, could we do that?

That would be another issue then

> Could you add a small reprex which shows the final plot?

From the test file:
```r
task = tsk("iris")$select(c("Sepal.Length", "Sepal.Width"))
learner = lrn("classif.rpart", predict_type = "prob")$train(task)
p = plot_prediction(learner, task, expand_range = 0.1)
expect_true(is.ggplot(p))
```

image

**Comment by mllg** [comment]
Is something important missing in comparison to the mlr version?

**Comment by tpielok** [comment]
I'm missing

- Highlighting of misclassified points 
- Different shapes according to which class a point belongs to
- 2d plotting capability for regression learners

The previous version also included an _internal_ CV, s.t. the test performance could be returned and points could be marked as misclassified from the "test"-perspective. I think this was a nice feature, but not a must-have.

**Comment by mllg** [comment]
This is a more general question:

We use two different data frames in the function, one for the raster and one for the points. This leads to a situation where I cannot manipulate the resulting plot anymore. E.g., if I want to reduce size of the plotted points, `+
 geom_point(size = 2)` uses the raster data.

Is there a generic solution to this? Would it help to merge the data.frames first?

**Comment by pat-s** [comment]
> That would be another issue then

Hm yes and no, if we keep adding content without it, the burden to use it/the work to redo it becomes bigger and bigger.

You can find an example here to get started

https://github.com/mlr-org/mlr3spatiotempcv/blob/7f7af14cdc5ad0a42e99c434a2d56ac3e7bb6994/tests/testthat/test-autoplot.R#L11-L22

**Comment by jakob-r** [comment]
> Is there a generic solution to this? Would it help to merge the data.frames first?
Merging would not help. You can modify scales afterwards. So any aesthetic rendering can be modified afterwards. But the point size is not in data dependent (i.e. not inside the aesthetic). You could make it dependent on a column that is constant I guess?

Or you can hack something like that: `p$layers[[2]]$aes_params$size = 10`

**Comment by jakob-r** [comment]
> Highlighting of misclassified points

Makes sense. We could change the border color. But you can already see if a point of the wrong color is in a specific area

> Different shapes according to which class a point belongs to

So the prediction changes the shape? Ok, we have 5 different shapes available that we can fill. We just need to add `scale_shape_manual(21:25)` I guess.

> 2d plotting capability for regression learners

Regression generally. 1d also.

> The previous version also included an internal CV, s.t. the test performance could be returned and points could be marked as misclassified from the "test"-perspective. I think this was a nice feature, but not a must-have.

Please no. That is doing to much and is totally confusing because you don't know which folds prediction is used to generate the raster. The only thing what makes sense is to have a plot for a holdout.

**Comment by tpielok** [comment]
> > Highlighting of misclassified points
> 
> Makes sense. We could change the border color. But you can already see if a point of the wrong color is in a specific area

Yes IMO a highlighted border color would definitively be easier to catch.

> > Different shapes according to which class a point belongs to
> 
> So the prediction changes the shape? Ok, we have 5 different shapes available that we can fill. We just need to add `scale_shape_manual(21:25)` I guess.

Sounds good to me

> > 2d plotting capability for regression learners
> 
> Regression generally. 1d also.

+1

> > The previous version also included an internal CV, s.t. the test performance could be returned and points could be marked as misclassified from the "test"-perspective. I think this was a nice feature, but not a must-have.
> 
> Please no. That is doing to much and is totally confusing because you don't know which folds prediction is used to generate the raster. The only thing what makes sense is to have a plot for a holdout.

Fine by me, you've got a point there.

**Comment by HeidiSeibold** [comment]
When do you think this will be available? As you may know we need this for the intro to ML course.

Thanks :sunflower:

**Comment by jakob-r** [comment]
One idea we have to discuss: We could have an API `autoplot(resample_object)` instead of the `plot_learner_prediction`. The re-sampling could be a holdout with 0%. Another advantage. This autoplot function would not do any heavy calculations.

**Comment by tpielok** [comment]
If you choose this approach, could we keep plot_learner_prediction as a helper function?
e.g.

```r
plot_learner_prediction = function(task, learner, ...){
    r =  resample(task, learner$clone(), rsmp("holdout", ratio = 1))
    autoplot(r, ...)
}
```

Then I would not be forced to always create a resampling object when I just want to do a simple plot.

**Comment by mllg** [comment]
> Then I would not be forced to always create a resampling object when I just want to do a simple plot.

It is not so much more if you compare it. And you would have to provide train+test indices yourself if you go without `resample()`.

**Comment by jakob-r** [comment]
Just noticed: We already have `autoplot.ResampleResult` -.- Should I use `type = "predict"`?
Also: @mllg But we agreed that because you would nearly always write this `resample()` it makes sense to have a wrapper (i.e. `plot_learner_prediction`)?

**Comment by mllg** [comment]
Let's just write the helper function (should only have a few lines) and then re-evaluate its usefulness.

**Comment by mllg** [comment]
Superseded by #14.

**Pull request closed without merging**
