### PR TITLE
patch distr6 breakages

### PR DESCRIPTION
**Pull request by RaphaelS1**

### CODE REVIEW

**Comment by RaphaelS1** [comment]
@mllg sorry I haven't worked with testing plots before so not sure how to fix these tests, any pointers?

**Comment by mllg** [comment]
No worries, we'll take over.

**Comment by mllg** [comment]
And TBH I also don't know how to repair `vidffr` here. Maybe it was a mistake after all to use it. :(

@be-marc do you know how to proceed?

Other open issues we should address before merging:
* Do not rely on deprecated reshape2
* Fix R CMD check warnings about undefined variables

**Comment by RaphaelS1** [comment]
Yeah sorry about reshape2. I couldn't get data.table melt to do the same thing, reshape2 is much more intuitive!

**Pull request merged**
