### PR TITLE
add dcalib to predictionsurv

### PR DESCRIPTION
**Pull request by RaphaelS1**
I would appreciate someone double checking the maths on this one before merging (no rush for this). I haven't seen this used before and it's an extension I've written from a new (2020) measure.

https://www.jmlr.org/papers/volume21/18-772/18-772.pdf - Sec 3.5, the measure itself I'll probably add to proba. The graphical calibration extension is quite nice and intuitive

Basically it plots the following:

x-axis: p = 0,0.1,...,0.9,1 (or with different bin-widths)
y-axis: sum(T_i <= F_i^-1(p))/100
where T_i is individual death-times and F_i^-1 is individual quantile functions.

Model is well-calibrated if this is close to the line x = y.

In words: a model is well-calibrated if 50% of the observations die before their predicted mean survival time and more generally if X% die before X/100 predicted quantile.

### CODE REVIEW

**Comment by mllg** [comment]
The example plot doesn't look calibrated. This is expected, right?

**Review by mllg — APPROVED** [review]

**Comment by RaphaelS1** [comment]
Yeah I considered checking for other examples that were calibrated

**Comment by mllg** [comment]
@adibender can you review the code?

**Comment by RaphaelS1** [comment]
Ah I forgot about this. I'm confident about the measure itself (I've since found similar in other papers) but of course code review still appreciated

**Comment by adibender** [comment]
> @adibender can you review the code?

yes, will do.

**Comment by adibender** [comment]
I've run some sanity checks. measure `surv.dcalib` shoud be lowest for the "better" model, but that doesn't appear to be the case. Similarly, the calibration curve for the model with coviariates doesn't appear to be better than the one for the KM. Also appears to be somewhat sensitive to the seed. Sometimes I had values for D-Calib of 200 (on average): 

``` r
library(pammtools)
library(survival)

## simulate data
# set number of observations/subjects
n <- 500
# create data set with variables which will affect the hazard rate.
df <- cbind.data.frame(x1 = runif (n, -3, 3), x2 = runif (n, 0, 6))
# the formula which specifies how covariates affet the hazard rate
f0 <- function(t) {
 dgamma(t, 8, 2) *6
}
form <- ~ -3.5 + f0(t) -0.5*x1 + sqrt(x2)
set.seed(311428)
sim_df <- sim_pexp(form, df, 1:10)
sim_df_test <- sim_pexp(form, df, 1:10)
sim_df$id <- sim_df_test$id <- NULL
head(sim_df)
#> # A tibble: 6 x 4
#>     time status     x1    x2
#>    <dbl>  <int>  <dbl> <dbl>
#> 1  3.55       1 -1.30  4.31 
#> 2  3.53       1  2.53  5.50 
#> 3  3.61       1 -1.38  2.85 
#> 4  0.618      1 -1.74  0.940
#> 5  0.534      1  1.44  3.84 
#> 6 10          0  0.720 0.226

# overall survival 
plot(survfit(Surv(time, status)~1, data = sim_df ))
```



``` r

## mlr 3
library(mlr3)
library(mlr3proba)
library(mlr3viz)

tsk_sim <- TaskSurv$new(
  id      = "sim1",
  backend = sim_df,
  time    = "time",
  event  = "status")
tsk_sim_test <- TaskSurv$new(
  id      = "sim1_test",
  backend = sim_df_test,
  time    = "time",
  event  = "status")


lrn_km <- lrn("surv.kaplan")
lrn_cph <- lrn("surv.coxph")


rsmp <- rsmp("repeated_cv", folds = 5, repeats = 10)

bmr_grid <- benchmark_grid(
  task       = tsk_sim,
  learner    = list(lrn_km, lrn_cph),
  resampling = rsmp
)

bmr <- benchmark(bmr_grid)

msr_dcalib <- msr("surv.dcalib")
msr_ibs <- msr("surv.graf")
msr_cind <- msr("surv.cindex")

bmr$aggregate(list(msr_dcalib, msr_ibs, msr_cind))
#>    nr      resample_result task_id  learner_id resampling_id iters surv.dcalib
#> 1:  1 <ResampleResult[21]>    sim1 surv.kaplan   repeated_cv    50    11.10870
#> 2:  2 <ResampleResult[21]>    sim1  surv.coxph   repeated_cv    50    12.61947
#>    surv.graf surv.harrell_c
#> 1: 0.1521078      0.5000000
#> 2: 0.1098210      0.7341962
lrn_km$train(tsk_sim)
lrn_cph$train(tsk_sim)

pred_km <- lrn_km$predict_newdata(sim_df_test)
pred_cph <- lrn_cph$predict_newdata(sim_df_test)


autoplot(bmr, measure = msr_ibs)
```



``` r
autoplot(bmr, measure = msr_dcalib)
```



``` r

autoplot(pred_km, type = "dcalib")
```



``` r
autoplot(pred_cph, type = "dcalib")
```



<sup>Created on 2021-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by adibender** [comment]
@RaphaelS1 are there different references for the different calibration plots? Can you include both in the reference section

**Comment by RaphaelS1** [comment]
Summarising conversation from MM in reply to comments:

> I've run some sanity checks. measure surv.dcalib shoud be lowest for the "better" model, but that doesn't appear to be the case. Similarly, the calibration curve for the model with coviariates doesn't appear to be better than the one for the KM. Also appears to be somewhat sensitive to the seed. Sometimes I had values for D-Calib of 200 (on average):

1. The measure `surv.dcalib` is completely different from the plot so should be discussed in proba.
2. Survival calib measures have poor interpretation overall and in general multiple measures of calibration should be used alongside discrimination and scoring rules to capture a true evaluation of models (more a statement about the state of field than the code)
3. Large values aren't surprising given sum of squares (i.e. only need one quantile slightly misspecified)

> are there different references for the different calibration plots? Can you include both in the reference section

Only references for dcalib but even that is not fully described in the paper but a natural calibration. As for comparison to KM this is a natural generalisation from the 'calibration slope'

**Comment by t-r-uth** [comment]
Hi, I would like to check if autoplot.PredictionSurv. is still available in the latest mlr3viz (0.5.10). I can't seem to run the code above eg. autoplot(pred_cph, type = "dcalib") anymore. And does this autoplot function able to plot surv.rpart learner?

**Comment by RaphaelS1** [comment]
Hi @t-r-uth it's been moved to mlr3proba!

**Pull request merged**
