### PR TITLE
Add `theme_mlr3()`

### PR DESCRIPTION
**Pull request by pat-s**
As discussed during the workshop. For some quick previews, the README can be rendered.

- Updated README with new example plots
- Added section how to change the current theme
- Fixed some (minor) issues in some plots
- Adds {scales} as dep because of `pretty_breaks()`

Turned off R-devel runner due to issues with {vdiffr}. R-devel issues seem to be a reoccuring thing and we should be fine checking r-release here only until these are resolved.

image

### CODE REVIEW

**Comment by mllg** [comment]
This isn't right?

```r
library(mlr3)
task = tsk("iris")
autoplot(task, type = "pairs")
```

**Comment by mllg** [comment]
I guess we should contact the GGally authors and ask if there is a way to change the colors or if they can provide a way to do this in a future version. Having multiple color themes in a single plot does not seem to be an improvement.

**Comment by pat-s** [comment]
@mllg I fixed the theme issues with `GGally` - all plots are now styled consistently throughout the full plot.

**Comment by pat-s** [comment]
I don't understand the current size warning for the snaps - they are 10KB on my local disk 🤔

**Comment by mllg** [comment]
> I don't understand the current size warning for the snaps - they are 10KB on my local disk thinking

The file path is too long. Starting from the package root, you may only use up to 100 characters.

**Comment by pat-s** [comment]
@mllg Thanks!  Fixed.

**Comment by be-marc** [comment]
I commented on some plots e.g. `# no theme colors `:

```r
library(mlr3)
library(mlr3viz)

# BenchmarkResult.R
tasks = tsks(c("pima", "sonar"))
learner = lrns(c("classif.featureless", "classif.rpart"), predict_type = "prob")
resampling = rsmps("cv")
object = benchmark(benchmark_grid(tasks, learner, resampling))

autoplot(object)
autoplot(object$clone(deep = TRUE)$filter(task_ids = "pima"), type = "roc") # no theme colors
autoplot(object$clone(deep = TRUE)$filter(task_ids = "pima"), type = "prc") # no theme colors

# Filter.R
library(mlr3filters)

task = tsk("mtcars")
f = flt("correlation")
f$calculate(task)

autoplot(f, n = 5)

# LearnerClassifGlmnet.R
library(mlr3learners)

task = tsk("sonar")
learner = lrn("classif.glmnet")
learner$train(task)
autoplot(learner)

task = tsk("mtcars")
learner = lrn("regr.glmnet")
learner$train(task)
autoplot(learner)

# LearnerClassifRpart.R
task = tsk("iris")
learner = lrn("classif.rpart", keep_model = TRUE)
learner$train(task)
autoplot(learner) # no theme colors

task = tsk("mtcars")
learner = lrn("regr.rpart", keep_model = TRUE)
learner$train(task)
autoplot(learner)

# LearnerClustHierarchical.R
library(mlr3cluster)

task = mlr_tasks$get("usarrests")

learner = mlr_learners$get("clust.agnes")
learner$train(task)
autoplot(learner) # warning message

learner = mlr_learners$get("clust.diana")
learner$train(task)
autoplot(learner, k = learner$param_set$values$k, rect_fill = TRUE, rect = TRUE, rect_border = "red") # no theme colors and warning message

learner = mlr_learners$get("clust.hclust")
learner$train(task)
autoplot(learner, type = "scree")

# OptimInstanceSingleCrit.R
library(bbotk)
library(paradox)

fun = function(xs) {
  c(y = -(xs[[1]] - 2)^2 - (xs[[2]] + 3)^2 + 10)
}
domain = ps(
  x1 = p_dbl(-10, 10),
  x2 = p_dbl(-5, 5)
)
codomain = ps(
  y = p_dbl(tags = "maximize")
)
obfun = ObjectiveRFun$new(
  fun = fun,
  domain = domain,
  codomain = codomain
)

instance = OptimInstanceSingleCrit$new(objective = obfun, terminator = trm("evals", n_evals = 20))

optimizer = opt("random_search", batch_size = 2)
optimizer$optimize(instance)

autoplot(instance, type = "performance")
autoplot(instance, type = "marginal", cols_x = "x1")
autoplot(instance, type = "parallel")
autoplot(instance, type = "pairs")

# PredictionClassif.R
task = tsk("spam")
learner = lrn("classif.rpart", predict_type = "prob")
object = learner$train(task)$predict(task)

autoplot(object)
autoplot(object, type = "roc")
autoplot(object, type = "prc")

# PredictionClust.R
library(mlr3cluster)

task = tsk("usarrests")
learner = lrn("clust.kmeans", centers = 3)
object = learner$train(task)$predict(task)

autoplot(object, task)

# PredictionRegr.R
task = tsk("boston_housing")
learner = lrn("regr.rpart")
object = learner$train(task)$predict(task)

autoplot(object) # no theme colors
autoplot(object, type = "histogram", binwidth = 1)
autoplot(object, type = "residual") # no theme colors

# PredictionSurv.R
library(mlr3proba)

learn = lrn("surv.coxph")
task = tsk("unemployment")
p = learn$train(task, row_ids = 1:300)$predict(task, row_ids = 301:400)

autoplot(p, type = "calib", task = task, row_ids = 301:400) # no theme colors
autoplot(p, type = "dcalib") # no theme colors

# ResampleResult.R
task = tsk("sonar")
learner = lrn("classif.rpart", predict_type = "prob")
resampling = rsmp("cv")
object = resample(task, learner, resampling)


autoplot(object)
autoplot(object, type = "histogram", bins = 30)
autoplot(object, type = "roc")
autoplot(object$prediction(), type = "roc") # no theme colors
autoplot(object, type = "prc") # no theme colors

task = tsk("iris")$select(c("Sepal.Length", "Sepal.Width"))
resampling = rsmp("cv", folds = 3)
object = resample(task, learner, resampling, store_models = TRUE)
autoplot(object, type = "prediction")

# TaskClassif.R
task = tsk("iris")

autoplot(task)
autoplot(task$clone()$select(c("Sepal.Length", "Sepal.Width")), type = "pairs") # yellow text is difficult to read
autoplot(task, type = "duo")

# TaskClust.R
library(mlr3cluster)

task = mlr_tasks$get("usarrests")

autoplot(task)

# TaskRegr.R
task = tsk("mtcars")
task$select(c("am", "carb"))

autoplot(task)
autoplot(task, type = "pairs")

# TaskDens.R
library(mlr3proba)
task = tsk("precip")

autoplot(task, bins = 15)
autoplot(task, type = "freq", bins = 15)
autoplot(task, type = "overlay", bins = 15) # no theme colors

# TaskSurv.R
library(mlr3proba)

task = tsk("lung")

autoplot(task)
autoplot(task, rhs = "sex")
autoplot(task, type = "duo")
```

**Comment by mllg** [comment]
How hard would it be to apply the theme to the remaining autoplots?

I also would like to suggest introducing the option `"mlr3viz.theme"` and helper function 
```r
get_mlr3_theme = function() {
  # package default: our custom theme
  getOption("mlr3viz.theme", default = theme_mlr3())
  # package default: no custom theme
  # getOption("mlr3viz.theme", default = NULL)
}
```
So that we can keep the code clean and just do `ggplot() + get_mlr3_theme()` everywhere.

**Comment by pat-s** [comment]
@be-marc Thanks for spotting!

@mllg This is a bit difficult as theming is one thing and coloring the other, i.e. while this might work WRT to the theme, color scales won't work because their specification differs based on the geom characteristics (color, fill, point, lines, etc).

I probably won't have time to tackle this in the next days.

**Comment by be-marc** [comment]
> @mllg This is a bit difficult as theming is one thing and coloring the other, i.e. while this might work WRT to the theme, color scales won't work because their specification differs based on the geom characteristics (color, fill, point, lines, etc).

I added a small helper `apply_theme()` that takes the theme and color scales and applies them to the plot when `options(mlr3.theme = TRUE)`. The default is `TRUE`.

**Comment by pat-s** [comment]
Cool!
This also needs to be documented quite prominently. Maybe even in all `autoplot()` functions? We can use a shared `man-roxygen` note or section for this?

@be-marc Looks like some plots need to be re-validated.

**Pull request merged**
